### PR TITLE
DTPORTAL-16506: Entering # on Currency Question should not match

### PR DESCRIPTION
**Pull request by sfgeorge**
PR cloudvox/apptastic#644 ensured that the Digits grammar always requires at least one digit in order to consider a grammar / Regular Expression to `:match`.

This current PR does similar for the Currency grammar - to require at least one digit in order to consider a grammar / Regular Expression to `:match`.

### CODE REVIEW

**Comment by sfgeorge** [comment]
@faraocious Can you review this for me, mate?

Cc: @gfaza @rkodali2 @dprabh-dlgtech @mikeheidenreich

**Comment by sfgeorge** [comment]
Sorry @faraocious, just realized that you are on PTO today.

@zmjohnson42 could I ask you to review this for me?  [Grammars](https://www.lumenvox.com/knowledgebase/index.php?/article/AA-01061/0) are analogous to Regular Expressions, but it's a whole different language.  Please feel free to hit me up with Qs!

**Comment by sfgeorge** [comment]
@zmjohnson42 this is a lot easier to digest as a set of Regular Expressions, I think.

**Before the Change**

Essentially, [this Grammar](https://github.com/adhearsion/ruby_speech/blob/3.0.0/lib/ruby_speech/grxml/builtins.rb#L92-L110) used to be satisfied as being "matched" if input matched the following pattern:

`/[0-9]*(\*[0-9]{,2})?/`
The _intent_ was to match integers, followed by an optional `*` as a decimal point and up to 2 decimal values (e.g. `9` or `9*99`);  as well as to allow someone to shorthand a value less than a dollar with something like `*99`.

However, this lax Regular Expression above even "matches" for an input of empty string - and it should not.

----

**After the Change**

And now, [this Grammar](https://github.com/sfgeorge/ruby_speech/blob/DTPORTAL-16506-pound-on-currency/lib/ruby_speech/grxml/builtins.rb#L92-L125) is satisfied as being "matched" if input matches _either one_ of the following 2 patterns:
1. `/\*[0-9]{1,2}/` (a.k.a. `less_than_one`)
2. or `/[0-9]{1,}(\*[0-9]{,2})?/` (a.k.a. `one_or_more`)

By adding this level of specificity, one of the benefits is that neither pattern 1. nor 2. permits empty string, which is the intent of the PR here.

**Comment by sfgeorge** [comment]
FYI build failures were pre-existing before this PR was started.  I am fixing those build failures in adhearsion/ruby_speech#56, rather than in this PR.

**Comment by sfgeorge** [comment]
@gfaza Can you review this for me good sir?

**Comment by gfaza** [comment]
👍

**Review by zmjohnson42 — COMMENTED** [review]
I am not too familiar with how these rules and matches are used, but looking at just this GRXML change the resultant output is going from

**Old**
```
<rule id="currency" scope="public">
  <item repeat="0-"><ruleref uri="#digit"></item>
  <item repeat="0-1">
    <item>*</item>
    <item repeat="0-2"><ruleref uri="#digit"></item>
  </item>
</rule>
```

To **New**
```
<rule id='currency' scope='public>
  <one-of>
    <item><ruleref uri="#less_than_one"></item>
    <item><ruleref uri="#one_or_more"></item>
  </one-of>
</rule>

<rule id="less_than_one">
  <item>*</item>
  <item repeat="1-2"><ruleref uri="#digit"></item>
</rule>

<rule id="one_or_more">
  <item repeat="1-"><ruleref uri="#digit"></item>
  <item repeat="0-1">
    <item>*</item>
    <item repeat="0-2"><ruleref uri="#digit"></item>
  </item>
</rule>
 ```

Essentially swapping out the old currency rules that where matching directly on the digits, to two "new" rules that handle `one-of` the previous "repeat" rules plus a preceding wildcard, in which that wildcard is enforcing numerical values instead of strings.

**Comment by sfgeorge** [comment]
@zmjohnson42  That's exactly right, mate. Thanks so much.

**Pull request merged**
