### PR TITLE
Story 10543 pulling adhearsion develop

### PR DESCRIPTION
**Pull request by gfaza**
This is a pull of `develop` to `dialogtech/support/3.0.0`, in order to be compatible with `activesupport >= 5`.  very much the same code that my personal branch has at the moment.  once this is merged, we can update `web` to point to this repo rather than mine, at https://github.com/Invoca/web/blob/7e20863f9c1c174df3b5393daa975d9a1642c108/Gemfile#L407

### CODE REVIEW

**Review by luanzeba — APPROVED** [review]
Looks good. Since this follows a project maintained by someone else, should we disable hound to avoid getting a lot of comments on code that wasn't written by us?

**Comment by gfaza** [comment]
> Looks good. Since this follows a project maintained by someone else, should we disable hound to avoid getting a lot of comments on code that wasn't written by us?
sounds good to me!  @jebentier, can you  disabling `hound` something you can help with

**Comment by gfaza** [comment]
geez - github went crazy on me.  re-opened, b/c i don't want it closed.

@jebentier, is disabling `hound` something you can help with, or could you recommend the right team to assist with that?

**Comment by jebentier** [comment]
I've gone ahead and disabled hound for this project

**Pull request merged**
