### PR TITLE
DTPORAL-16546: Avoid EmptyStackException

### PR DESCRIPTION
**Pull request by sfgeorge**
Avoid an unpleasant `Java::JavaUtil::EmptyStackException: <empty error message>` Exception when multiple threads invoke `match` on the same matcher.

At the root of the problem is that `grammar.root_rule` is quite racey.  This PR does not actually fix that - but it makes it no longer an issue (for ruby_speech at least) by caching the place where it is otherwise frequently used - when `#regexp_content` is rebuilt over-and-over again with each match operation.

By caching `@regexp_content`, we avoid the raceyness of `grammar.root_rule` and avoid the following exception:

```
[2019-08-13 20:44:29.122] ERROR Celluloid: Actor crashed!
Java::JavaUtil::EmptyStackException:
org.apache.xml.utils.ObjectStack.peek(ObjectStack.java:130)
org.apache.xpath.XPathContext.getNamespaceContext(XPathContext.java:922)
org.apache.xpath.axes.PredicatedNodeTest.executePredicates(PredicatedNodeTest.java:330)
org.apache.xpath.axes.UnionChildIterator.acceptNode(UnionChildIterator.java:128)
org.apache.xpath.axes.BasicTestIterator.nextNode(BasicTestIterator.java:174)
org.apache.xpath.axes.NodeSequence.nextNode(NodeSequence.java:335)
org.apache.xpath.axes.NodeSequence.runTo(NodeSequence.java:494)
org.apache.xml.dtm.ref.DTMNodeList.<init>(DTMNodeList.java:81)
org.apache.xpath.objects.XNodeSet.nodelist(XNodeSet.java:346)
nokogiri.XmlXpathContext.tryGetNodeSet(XmlXpathContext.java:188)
nokogiri.XmlXpathContext.node_set(XmlXpathContext.java:161)
nokogiri.XmlXpathContext.evaluate(XmlXpathContext.java:128)
nokogiri.XmlXpathContext$INVOKER$i$evaluate.call(XmlXpathContext$INVOKER$i$evaluate.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:199)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.invokeOther11:evaluate(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:198)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$xpath_impl$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:198)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$xpath_impl$0$__VARARGS__(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.invokeOther10:xpath_impl(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:179)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$xpath_internal$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:179)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$xpath_internal$0$__VARARGS__(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.invokeOther1:xpath_internal(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:154)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$xpath$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:154)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:110)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.niceogiri_minus_1_dot_1_dot_2.lib.niceogiri.core_ext.nokogiri.invokeOther17:nokogiri_xpath(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/niceogiri-1.1.2/lib/niceogiri/core_ext/nokogiri.rb:37)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.niceogiri_minus_1_dot_1_dot_2.lib.niceogiri.core_ext.nokogiri.RUBY$method$xpath$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/niceogiri-1.1.2/lib/niceogiri/core_ext/nokogiri.rb:37)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.invokeOther0:xpath(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:165)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.gems.nokogiri_minus_1_dot_10_dot_4_minus_java.lib.nokogiri.xml.searchable.RUBY$method$at_xpath$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/gems/nokogiri-1.10.4-java/lib/nokogiri/xml/searchable.rb:165)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.RubyClass.finvoke(RubyClass.java:505)
org.jruby.RubyBasicObject.send(RubyBasicObject.java:1740)
org.jruby.RubyKernel.send(RubyKernel.java:2193)
org.jruby.RubyKernel$INVOKER$s$send.call(RubyKernel$INVOKER$s$send.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:80)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.generic_element.invokeOther3:send(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/generic_element.rb:268)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.generic_element.RUBY$method$method_missing$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/generic_element.rb:268)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.runtime.Helpers$MethodMissingMethod.call(Helpers.java:393)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:212)
org.jruby.runtime.callsite.CachingCallSite.callMethodMissing(CachingCallSite.java:430)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:357)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:201)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.grammar.invokeOther8:at_xpath(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/grammar.rb:217)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.grammar.RUBY$method$rule_with_id$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/grammar.rb:217)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.grammar.invokeOther1:rule_with_id(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/grammar.rb:89)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.grammar.RUBY$method$root_rule$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/grammar.rb:89)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:104)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:123)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.invokeOther2:root_rule(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:99)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.RUBY$method$regexp_content$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:99)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:104)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:123)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.invokeOther2:regexp_content(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:123)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.RUBY$method$find_tag$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:123)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.invokeOther4:find_tag(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:117)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.RUBY$method$interpret_utterance$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:117)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.invokeOther6:interpret_utterance(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:113)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.RUBY$method$match_for_buffer$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:113)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:127)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:189)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
org.jruby.RubyClass.finvoke(RubyClass.java:808)
org.jruby.runtime.Helpers.invoke(Helpers.java:443)
com.adhearsion.ruby_speech.RubySpeechGRXMLMatcher.find_match(RubySpeechGRXMLMatcher.java:42)
com.adhearsion.ruby_speech.RubySpeechGRXMLMatcher$INVOKER$i$1$0$find_match.call(RubySpeechGRXMLMatcher$INVOKER$i$1$0$find_match.gen)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.invokeOther1:find_match(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:93)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.ruby_speech_minus_8acfb8f3a976.lib.ruby_speech.grxml.matcher.RUBY$method$match$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/ruby_speech-8acfb8f3a976/lib/ruby_speech/grxml/matcher.rb:93)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.adhearsion_minus_8c6c81db8717.lib.adhearsion.translator.asterisk.component.dtmf_recognizer.invokeOther3:match(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/adhearsion-8c6c81db8717/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb:76)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.adhearsion_minus_8c6c81db8717.lib.adhearsion.translator.asterisk.component.dtmf_recognizer.RUBY$method$get_match$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/adhearsion-8c6c81db8717/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb:76)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:104)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:123)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:137)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.adhearsion_minus_8c6c81db8717.lib.adhearsion.translator.asterisk.component.dtmf_recognizer.invokeOther4:get_match(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/adhearsion-8c6c81db8717/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb:52)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.adhearsion_minus_8c6c81db8717.lib.adhearsion.translator.asterisk.component.dtmf_recognizer.RUBY$method$\=\^\^$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/adhearsion-8c6c81db8717/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb:52)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.adhearsion_minus_8c6c81db8717.lib.adhearsion.translator.asterisk.component.dtmf_recognizer.RUBY$method$\=\^\^$0$__VARARGS__(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/adhearsion-8c6c81db8717/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.RubyKernel.public_send(RubyKernel.java:1953)
org.jruby.RubyKernel$INVOKER$s$0$0$public_send.call(RubyKernel$INVOKER$s$0$0$public_send.gen)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:296)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:82)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.calls.invokeOther6:public_send(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/calls.rb:26)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.calls.RUBY$method$dispatch$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/calls.rb:26)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.calls.RUBY$method$dispatch$0$__VARARGS__(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/calls.rb)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:91)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1154)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.calls.invokeSuper2:dispatch(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/calls.rb:79)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.calls.RUBY$method$dispatch$0(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/calls.rb:79)
org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:117)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:339)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.cell.invokeOther1:dispatch(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/cell.rb:60)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.cell.RUBY$block$invoke$1(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/cell.rb:60)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
org.jruby.runtime.Block.yieldSpecific(Block.java:134)
org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:141)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.cell.RUBY$block$task$1(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/cell.rb:71)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
org.jruby.runtime.Block.yieldSpecific(Block.java:134)
org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:141)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.actor.RUBY$block$task$1(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/actor.rb:357)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
org.jruby.runtime.Block.yieldSpecific(Block.java:134)
org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:141)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.tasks.RUBY$block$initialize$1(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/tasks.rb:57)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.IRBlockBody.yieldSpecific(IRBlockBody.java:85)
org.jruby.runtime.Block.yieldSpecific(Block.java:134)
org.jruby.ir.targets.YieldSite.yieldSpecific(YieldSite.java:141)
srv.phone.apptastic.shared.bundle.jruby.$2_dot_5_dot_0.bundler.gems.celluloid_minus_df512cbbe68d.lib.celluloid.tasks.task_fiber.RUBY$block$create$1(/srv/phone/apptastic/shared/bundle/jruby/2.5.0/bundler/gems/celluloid-df512cbbe68d/lib/celluloid/tasks/task_fiber.rb:14)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:146)
org.jruby.runtime.BlockBody.yield(BlockBody.java:122)
org.jruby.runtime.Block.yieldArray(Block.java:177)
org.jruby.ext.fiber.ThreadFiber.lambda$createThread$0(ThreadFiber.java:281)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by sfgeorge** [comment]
@gfaza @kares Can you review this for me?

**Comment by kares** [comment]
LGTM, and it will likely be fine in the large majority of cases.
the change makes sense even if there wasn't an issue, but I still see ways of making sure we never expose the same doc (since the `grammar` will be shared by matchers) in possibly concurrent xpath operations. we should likely do that on a higher level (in adhearsion).

**Comment by sfgeorge** [comment]
Thanks man.

> but I still see ways of making sure we never expose the same doc (since the grammar will be shared by matchers) in possibly concurrent xpath operations. we should likely do that on a higher level (in adhearsion).

I think we should be safe there since [the call to grammar = RubySpeech::GRXML.from_uri(uri)](https://github.com/cloudvox/adhearsion/blob/dialogtech/support/3.0.0.rc1/lib/adhearsion/translator/asterisk/component/dtmf_recognizer.rb#L23) in adhearsion produces a new Grammar instance, and ties that in a 1-to-1 fashion per cached grammar.  There should be no case where multiple Matchers share the same instance of a Grammar.

**Review by gfaza — APPROVED** [review]
👍

**Comment by sfgeorge** [comment]
@mattcar Can you merge this for me?

FYI @rkodali2, once this is merged then cloudvox/apptastic#651 will be properly updated to point to the latest & greatest of ruby_speech's `dialogtech/support/3.0.0` branch.

**Pull request merged**
